- name: Common Bits 
  hosts: all
  tasks:
      - name: Copy the sudoers file
        copy: src=files/passwordless-sudo dest=/etc/sudoers.d/passwordless-sudo owner=root group=root mode=0440 backup=no
#     - name: Upgrade currently installed packages
#       apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"
      - name: Install common packages
        apt: "name={{ item }} state=present"
        with_items:
           - python-apt
           - curl
           - telnet
           - apt-transport-https
           - wget

- name: Webmin 
  hosts: docker
  tasks:
      - name: Install Webmin keys
        apt_key: url='http://www.webmin.com/jcameron-key.asc' state=present
      - name: Install primary Webmin repository
        apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' state=present
      - name: Install secondary Webmin repository
        apt_repository: repo='deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib' state=present
      - name: Install Webmin software
        apt: name=webmin state=latest

