- name: Common Bits 
  hosts: all
  tasks:
      - name: Copy the sudoers file
        copy: src=files/passwordless-sudo dest=/etc/sudoers.d/passwordless-sudo owner=root group=root mode=0440 backup=no
#     - name: Upgrade currently installed packages
#       apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"
      - name: Install common packages
        apt: "name={{ item }} state=present"
        with_items:
           - python-apt
           - curl
           - telnet
           - apt-transport-https
           - wget
